version: '3.2'
services:
  rasa:
    image: rasa/rasa:2.3.4-full
    ports:
      - "5005:5005"
    volumes:
      - ./:/app
    command: run -vv
  rasa-action-server:
    build: ./actions
    volumes:
      - ./actions:/app/actions
    expose:
      - "5055"